mode: full

plots:
  t_sne: true
  silhouette: true
  clustering: true
  clustering_based_jm: true
  accuracy_to_silhouette: true

dataset:
  dataset_path: ./Model/Datasets/Cardiotocography.csv
  train_test_split: 75-25
  label_column_str: class

k_fold:
  n_splits: 2
  shuffle: true

t_sne:
  n_iter: 1000
  perplexity: 15

k_medoids:
  method: pam